# Generated by Django 4.1.2 on 2022-11-11 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmember',
            options={'ordering': ['id'], 'verbose_name': 'Пользователь чата', 'verbose_name_plural': 'Пользователи чата'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='sent_to',
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message', to='chats.chat', verbose_name='чат'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatmember_message_sf', to='chats.chatmember', verbose_name='отправитель'),
        ),
    ]
