# Generated by Django 4.1.2 on 2022-10-21 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'чат', 'verbose_name_plural': 'чаты'},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='title',
        ),
        migrations.AddField(
            model_name='chat',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='first_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_user', to=settings.AUTH_USER_MODEL, verbose_name='первый пользователь'),
        ),
        migrations.AddField(
            model_name='chat',
            name='second_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_user', to=settings.AUTH_USER_MODEL, verbose_name='второй пользователь'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='создатель чата'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='в архиве'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('sending_time', models.DateTimeField(auto_now_add=True, verbose_name='время отправки')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='chats.chat', verbose_name='чат')),
                ('sent_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_from', to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
                ('sent_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_to', to=settings.AUTH_USER_MODEL, verbose_name='получатель')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]
