# Generated by Django 4.1.2 on 2022-10-29 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0004_remove_chat_author_alter_chat_first_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['id'], 'verbose_name': 'чат', 'verbose_name_plural': 'чаты'},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='first_user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='second_user',
        ),
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(related_name='chatuser_chat', to=settings.AUTH_USER_MODEL, verbose_name='пользователи'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='прочитано'),
        ),
    ]
