# Generated by Django 4.1.2 on 2022-10-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatuser',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AddField(
            model_name='chatuser',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], default='', max_length=1, verbose_name='пол'),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='город'),
        ),
    ]
