# Generated by Django 4.1.2 on 2022-10-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_chatuser_options_chatuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatuser',
            options={'ordering': ['id'], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
